version: '3.8'

services:
  # Frontend Angular service
  frontend:
    build: 
      context: ./coach-2B-5-frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - app-network

  # Backend Symfony service
  backend:
    build: 
      context: ./coach-2B-5-backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./coach-2B-5-backend:/var/www
    depends_on:
      - mariadb
    environment:
      DATABASE_URL: mysql://app:!ChangeMe!@database:3306/app?serverVersion=mariadb-10.11.2
    networks:
      - app-network

  mariadb:
    image: mariadb:latest
    container_name: mariadb_server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - ./data:/data
      - ./mariadb_data:/var/lib/mysql
      - ./sql_import:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

networks:
  app-network:
    driver: bridge

volumes:
  database_data:
